<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class QuestionsTableSeeder extends Seeder
{
    public function run()
    {
        $questions = [
            "Saya Senang menghabiskan waktu untuk  menemukan  potensi kolaborasi  antara orang-orang atau ide.",
            "Saya sangat bersemangat  saat tahu bahwa pekerjaan saya akan berdampak besar bagi hidup orang lain.",
            "Saya senang mencoba pendekatan baru walaupun belum ada yang pernah melakukannya sebelumnya.",
            "Saya bangga jika dapat menjaga nilai-nilai budaya agar tidak hilang ditelan zaman.",
            "Saya peduli terhadap kelompok yang terpinggirkan dan ingin memberdayakan mereka.",
            "Saya sangat menikmati  saat bisa membuat orang merasa lebih baik setelah berbincang dengan Saya",
            "Saya senang menghabiskan waktu untuk mengajarkan sesuatu dengan cara yang membuat orang lain semangat belajar.",
            "Saya senang menghabiskan waktu  untuk mengikuti perkembangan  teknologi dan cara baru menyelesaikan masalah.",
            "Saya sangat bersemangat jika dapat membuka mata banyak orang melalui cerita yang menyentuh",
            "Saya sangat bersemangat  saat menginspirasi dan mengaktifkan potensi kelompok.",
            "Saya ingin terus belajar tentang cara negara atau organisasi publik dijalankan.",
            "Saya senang ikut berkontribusi menjaga lingkungan dan planet ini.",
            "Saya senang  memikirkan cara mengubah kebijakan atau struktur besar.",
            "Saya ingin terlibat dalam perumusan kebijakan berbasis riset dan data.",
            "Saya sangat tertarik membantu orang lain tumbuh secara pribadi atau profesional.",
            "Saya merasa nyaman bekerja di tengah beragam disiplin ilmu.",
            "Saya selalu ingin terlibat dalam politik, kebijakan, atau dunia pemerintahan.",
            "Saya ingin menghabiskan waktu menjadi juru bicara bagi yang tak terdengar.",
            "Saya menikmati mengekspresikan ide dan nilai saya melalui karya kreatif atau media.",
            "Saya ingin terus belajar tentang nilai-nilai yang lebih dalam dan bermakna secara batin.",
            "Saya bersedia menghabiskan waktu menyusun sistem, proses, atau arsitektur kerja yang rapi.",
            "Saya senang terlibat dalam pekerjaan yang memberi dampak jangka panjang",
            "Saya ingin terus belajar tentang hal-hal baru melalui eksperimen.",
            "Saya tertarik secara mendalam pada akar budaya sebagai sumber inspirasi dan kebijaksanaan",
            "Saya ingin terus mempelajari hal-hal yang terkait dengan pada coaching, mentoring, dan pengembangan manusia.",
            "Saya selalu ingin terlibat dalam membantu orang yang mengalami luka—fisik, mental, atau emosional.",
            "Saya merasa waktu cepat berlalu saat berusaha menyederhanakan hal rumit jadi mudah dimengerti.",
            "Saya tak pernah bosan memikirkan masa depan dan membuat solusi yang belum pernah ada.",
            "Saya senang ikut terlibat menyuarakan hal-hal penting lewat media atau kampanye.",
            "Saya sangat bergairah saat menjadi penggerak di tengah masyarakat, jaringan sosial atau di dalam tim.",
            "Saya siap bertanggung jawab dalam posisi yang mempengaruhi masyarakat luas",
            "Saya ingin terus belajar tentang perlindungan lingkungan sebagai tanggung jawab moral.",
            "Saya ingin menghabiskan waktu untuk menciptakan sistem baru yang lebih adil untuk semua",
            "Saya merasa paling hidup saat bisa menyalurkan ekspresi personal saya.",
            "Saya berbahagia saat melihat orang berkembang karena bantuan saya.",
            "Saya tertarik secara mendalam pada upaya mencari solusi terbaik dengan menggabungkan bidang-bidang ilmu yang tak umum.",
            "Saya menikmati saat memikirkan solusi hijau atau ramah lingkungan.",
            "Saya bersemangat saat melakukan pekerjaan yang selaras dengan keyakinan spiritual saya.",
            "Saya senang menghabiskan waktu menyampaikan ide dan perasaan lewat karya kreatif.",
            "Saya tak pernah bosan menggabungkan berbagai sumber pengetahuan menjadi solusi.",
            "Saya rasa saya akan sangat menikmati pekerjaan membangun sesuatu yang tahan lama dan bisa direplikasi.",
            "Saya lebih tertarik pada nilai dan kontribusi dari suatu pekerjaan ketimbang keuntungan semata.",
            "Saya ingin terlibat dalam budaya kerja yang lentur, dinamis, dan eksperimental.",
            "Saya senang mempelajari sejarah, bahasa, atau tradisi masyarakat.",
            "Saya senang jika dapat berkontribusi dalam perubahan sosial yang lebih adil.",
            "Saya senang menghabiskan waktu untuk merawat, menyembuhkan, atau mendampingi proses pemulihan orang lain.",
            "Saya merasa bersemangat saat membantu orang lain memahami sesuatu yang baru.",
            "Saya sangat tertarik untuk menjadi pencipta terobosan.",
            "Saya sangat bangga jika dapat menggunakan media untuk menyuarakan keadilan.",
            "Saya senang menjadi penghubung yang mempercepat terjadinya kolaboratif antara dua pihak atau lebih.",
            "Saya merasa terpanggil untuk memimpin demi kebaikan bersama.",
            "Saya rela menghabiskan waktu untuk mengkampanyekan kepedulian terhadap kelestarian lingkungan.",
            "Saya senang menghabiskan waktu berpikir tentang sistem besar dan dampaknya dalam jangka panjang.",
            "Saya menikmati menggabungkan ilmu atau bidang yang berbeda-beda.",
            "Saya senang menghabiskan waktu untuk refleksi dan nyari makna dari pengalaman hidup.",
            "Saya sangat tertarik pada usaha memadukan berbagai pengetahuan guna memahami sesuatu secara lebih dalam.",
            "Saya menikmati memberi dorongan dan insight agar orang dapat semakin maju.",
            "Saya ingin terus mempelajari isu-isu strategis dan kebijakan publik.",
            "Saya tertarik pada kekuatan estetika dan simbol dalam menyampaikan pesan.",
            "Saya menikmati saat melakukan sesuatu karena keyakinan, bukan hanya logika.",
            "Saya sangat bersemangat bekerja mengembangkan model atau kerangka kerja yang terstruktur.",
            "Saya ingin terlibat dalam proyek yang bermanfaat secara sosial dan lingkungan.",
            "Saya tertarik untuk jadi pemimpin yang adaptif dan kreatif.",
            "Saya sangat menikmati saat menggali akar identitas dan cerita komunitas.",
            "Saya selalu bersemangat saat membela hak orang lain.",
            "Saya merasa damai saat bisa membantu orang menjadi pulih kembali.",
            "Saya sangat menikmati aktivitas belajar menyebarkan ilmu.",
            "Saya akan bangga jika dapat terlibat dalam eksperimen dengan ide yang visioner dan out of the box.",
            "Saya bersemangat membuat cerita yang bisa menggerakkan perubahan sosial.",
            "Saya merasa bersemangat saat melihat orang terkoneksi dan saling menguatkan.",
            "Saya tertarik secara mendalam untuk menjadi pemimpin yang jujur dan bijak agar dapat membawa perubahan besar.",
            "Saya punya ketertarikan yang mendalam pada isu ekologi, energi hijau, dan gaya hidup berkelanjutan.",
            "Saya sangat senang jika dapat terlibat dalam aktivitas mengubah sistem yang rusak.",
            "Saya ingin ikut terlibat dalam menciptakan ruang yang mendukung pertumbuhan orang lain.",
            "Saya ingin ikut berperan dalam menciptakan kebijakan yang cerdas dan terukur.",
            "Saya sangat menikmati mencari hubungan yang tidak biasa antara konsep-konsep dari bidang yang berbeda.",
            "Saya tertarik mendorong perubahan besar di masyarakat, bukan hanya di permukaannya.",
            "Saya bangga jika dapat memberi solusi yang logis dan masuk akal.",
            "Saya bersemangat menginspirasi orang lain lewat karya yang saya ciptakan.",
            "Saya ingin terlibat dalam kerja-kerja yang membawa ketenangan batin dan kedamaian.",
            "Saya merasa puas seandainya semua hal bekerja secara efisien dan terorganisir.",
            "Saya peduli pada keberlanjutan dan dampak nyata dari apa yang saya kerjakan.",
            "Saya lebih bersemangat untuk \"coba dulu\" daripada terlalu banyak teori.",
            "Saya tak merasa bosan mengangkat nilai-nilai budaya lokal yang mulai terlupakan.",
            "Saya ingin terlibat memperjuangkan agar semua orang mendapatkan akses dan kesempatan yang setara.",
            "Saya merasa bangga jika dapat menciptakan lingkungan yang mendukung kesejahteraan.",
            "Saya tak pernah merasa bosan saat mengajar, membimbing, atau menjembatani pemahaman orang lain.",
            "Saya sangat bersemangat untuk dapat jadi pionir dalam menghadirkan masa depan yang lebih baik.",
            "Saya senang menghabiskan waktu membuat konten yang punya pesan sosial kuat.",
            "Saya tertarik secara mendalam pada kegiatan membuat fondasi sistem kerja yang bisa dijalankan oleh banyak orang.",
        ];

        foreach ($questions as $question) {
            DB::table('questions')->insert([
                'statement' => $question,
            ]);
        }
    }
}
